[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/payment/approve"
  to = "/.netlify/functions/payment-approve"
  status = 200

[[redirects]]
  from = "/payment/complete"
  to = "/.netlify/functions/payment-complete"
  status = 200

[[redirects]]
  from = "/payment/cancel"
  to = "/.netlify/functions/payment-cancel"
  status = 200
